//-----------------------------------------------------------------------------
// <copyright file="VLogServerSideError.Properties.cs" company="genuine">
//     Copyright (c) J.Baltikauskas. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------------
//  Author:     J.Baltikauskas
//  Date:       07/30/2008
//-----------------------------------------------------------------------------
namespace Vodca.Logging
{
    using System.Collections.Generic;

    /// <summary>
    ///     Represents a logical application error (as opposed to the actual 
    /// exception it may be representing).
    /// </summary>
    public sealed partial class VLogServerSideError
    {
        /// <summary>
        ///      Gets or sets a Session State
        /// </summary>
        public IDictionary<string, string> SessionState { get; set; }

        /// <summary>
        ///     Gets or sets a Application state
        /// </summary>
        public IDictionary<string, string> ApplicationState { get; set; }

        /// <summary>
        ///     Gets or sets a Http status description
        /// </summary>
        public string HttpStatusCodeDescription { get; set; }

        /// <summary>
        ///     Gets or sets a Server Variables
        /// </summary>
        public IDictionary<string, string> ServerVariableCollection { get; set; }

        /// <summary>
        ///     Gets or sets a Query String collection
        /// </summary>
        public IDictionary<string, string> QueryStringCollection { get; set; }

        /// <summary>
        ///     Gets or sets a Page Form Collection
        /// </summary>
        public IDictionary<string, string> FormCollection { get; set; }

        /// <summary>
        ///    Gets or sets a Page Cookie Collection 
        /// </summary>
        public IDictionary<string, string> CookiesCollection { get; set; }

        /// <summary>
        /// Gets or sets the page header collection.
        /// </summary>
        /// <value>The header collection.</value>
        public IDictionary<string, string> HeaderCollection { get; set; }

        /// <summary>
        /// Gets or sets the context items.
        /// </summary>
        /// <value>
        /// The context items.
        /// </value>
        public IDictionary<string, string> ContextItems { get; set; }

        /// <summary>
        ///     Gets or sets the HTML message generated by the web host (ASP.NET) 
        /// for the given error.
        /// </summary>
        public VXmlCData WebHostHtmlMessage { get; set; }
    }
}
